// src/content/mail.ts
// Two accounts. `personal` (qmercer.pb@) unlocks at gate 'mail' (act 2).
// `tidewater` (tidewater.ledger@) is the hidden whistleblower account,
// gate 'tidewater' (act 3). The unsent draft's ciphertext is generated by
// flip() from the plaintext in DESIGN.md; test-content.ts verifies the pair.

import type { Email } from '../models';

/** Login hint shown on the tidewater sign-in screen — itself in the cipher. */
export const TIDEWATER_HINT = 'gsv ylzg. dsvm sv dzh ylim.';
export const PERSONAL_ADDRESS = 'qmercer.pb@pelicanmail.com';
export const TIDEWATER_ADDRESS = 'tidewater.ledger@pelicanmail.com';

export const DRAFT_ID = 'em-draft';
export const DRAFT_SUBJECT_CIPHER = 'gl gsv lmob kvihlm dsl hgroo xzooh nv j';
export const DRAFT_BODY_CIPHER =
  'xzhvb. ru blf xzm ivzw gsrh, gsv tznv hgroo dliph, zmw hl wl blf. r zn mlg rm gsv dzgvi. ' +
  'r xlfow mlg hgzb, zmw r xlfow mlg dzim blf urihg. vor hlgl wrw mlg wildm yb zxxrwvmg. ' +
  'gsv nvm sv dlipvw uli ldm gsv gvhgh, gsv hsviruu, zmw gsv hglib. vevibgsrmt gsvb yfirvw ' +
  'rh yvsrmw gsrh zxxlfmg. dszg szkkvmh mvcg rh blfih gl xsllhv. hvmw rg zoo gl nziz ivbvh ' +
  'zmw hsv kirmgh gsv gifgs. li yfim rg zmw ovg nv hgzb z tslhg. gsviv rh z mfnyvi vmwrmt ' +
  'avil ulfi lmv gdl. hzb gsv low dliwh. olev, j';

export const EMAILS: Email[] = [
  // ——— personal inbox (act 2) ———
  {
    id: 'em-storage',
    account: 'personal',
    folder: 'inbox',
    from: 'PelicanMail',
    subject: 'Your storage is 90% full',
    when: 'Oct 9',
    body:
      'Hi Quinn,\n\nStorage used across your linked mailboxes is 90% full.\n\n' +
      '  • qmercer.pb@pelicanmail.com — 11.2 GB\n' +
      '  • tidewater.ledger@pelicanmail.com — 6.8 GB\n\n' +
      'Upgrade to PelicanMail+ to keep receiving mail.',
  },
  {
    id: 'em-invoices',
    account: 'personal',
    folder: 'inbox',
    from: 'Quinn Mercer',
    subject: 'Fwd: AP batch — September (do not delete)',
    when: 'Oct 3',
    body: 'forwarding to myself. if the audit asks: I only copied what was already true.',
    attachments: [
      {
        name: 'AP_batch_Sept.pdf',
        body:
          'HALLOWAY SEAFOOD CO. — ACCOUNTS PAYABLE, SEPTEMBER\n\n' +
          'INV 2209-A · Brennan Analytical Labs · $4,800.00\n' +
          '  "Quarterly water panel, Bed 7 & Bed 12. RESULTS ATTACHED —\n' +
          '   exceedances flagged, resample advised. Transmittal signed: R. Halloway."\n\n' +
          'INV 2209-B · Coastal Remediation LLC · $4,800.00\n' +
          '  "Consulting — resample & regulatory filing." Same date. No address.\n' +
          '  No phone. Registered agent: a PO box in Ardenwall.\n\n' +
          '[handwritten in margin] paid twice. once for the truth, once for the lie.',
      },
    ],
  },
  {
    id: 'em-newsletter',
    account: 'personal',
    folder: 'inbox',
    from: 'Tides & Ledgers Weekly',
    subject: 'FOIA’d: what the county won’t test',
    when: 'Sep 30',
    body:
      'This week: our records request on county shellfish-bed testing came back ' +
      '92% redacted — and the 8% is damning. Also: who is buying up dockside ' +
      'leases in Port Brennan?\n\nBy Mara Reyes, staff investigator.',
  },
  {
    id: 'em-pharmacy',
    account: 'personal',
    folder: 'inbox',
    from: 'Slater’s Pharmacy',
    subject: 'Itemized statement — Rx #7741',
    when: 'Oct 7',
    body:
      'Patient: MERCER, MARIANNE\nPrescriber: Dr. A. Okafor\n' +
      'Donepezil 10 mg, 90-day supply — $214.60 (insurance declined: plan lapsed)\n\n' +
      'Caregiver on file: Quinn Mercer.',
  },
  {
    id: 'em-bank',
    account: 'personal',
    folder: 'inbox',
    from: 'Port Brennan Credit Union',
    subject: 'Card alert: ATM withdrawal $400.00',
    when: 'Oct 8',
    body:
      'A withdrawal of $400.00 was made at BRENNAN MARKET ATM.\n' +
      'This is your second cash withdrawal this week. If this wasn’t you, call us.',
  },
  {
    id: 'em-mara-drop',
    account: 'personal',
    folder: 'inbox',
    from: 'Mara Reyes',
    subject: '(no subject)',
    when: 'Oct 18',
    visibleWhen: ['maraTrusted'],
    body:
      'What I have, so we’re even:\n\n' +
      '1. The 8% the county forgot to redact: Bed 7 closed for "maintenance" the ' +
      'week Eli Soto’s crew was sent to dredge it.\n' +
      '2. Coastal Remediation LLC was registered eleven days after the first bad ' +
      'panel. Its filing agent also handles Roy Halloway’s boat registrations.\n' +
      '3. The coroner’s office never tested Eli’s blood for what was in that water.\n\n' +
      'Quinn had the ledger side. I have the county side. Together it’s a case. ' +
      'Her half is still out there somewhere — she called it "the tide book." ' +
      'If you find an account, a folder, anything: that’s the match. Don’t hand ' +
      'it to Dunmore. He signed the Soto report.',
  },
  // ——— tidewater (act 3) ———
  {
    id: 'em-florist',
    account: 'tidewater',
    folder: 'inbox',
    from: 'Tidepool Florals',
    subject: 'Receipt — order #3117',
    when: 'Oct 14',
    body:
      'Thank you for your order!\n\n' +
      'Oct 14, 9:12 AM — paid IN STORE, cash.\n' +
      'Arrangement: white lilies.\n' +
      'Deliver to: M. Mercer, 44 Cormorant Ln, Port Brennan.\n' +
      'Card message: "like the fair. – Q"\n\n' +
      'Tidepool Florals — family-run since 1988. Come see us at the shop!',
  },
  {
    id: 'em-prepaid',
    account: 'tidewater',
    folder: 'inbox',
    from: 'NorthTel Prepaid',
    subject: 'Your prepaid line is active',
    when: 'Oct 9',
    body:
      'Welcome to NorthTel. Your prepaid SIM (line ending ···-0412) is active.\n' +
      'Loaded: 90 days talk & text. No contract. No names. That’s the NorthTel way.',
  },
  {
    id: 'em-tidebook',
    account: 'tidewater',
    folder: 'inbox',
    from: 'Quinn Mercer',
    subject: 'the tide book — everything, in order',
    when: 'Oct 11',
    body:
      'If someone I trust is reading this, the order matters:\n\n' +
      '1. Water panels, Bed 7/12, Feb–Sept — originals, before the swap.\n' +
      '2. The swapped versions filed with the county. Compare page 3s.\n' +
      '3. AP ledger: every Brennan Analytical invoice has a Coastal Remediation twin.\n' +
      '4. Crew schedule, April 12, 2025: E. Soto, dredge detail, Bed 7. ' +
      'He was in the water they already knew was poison.\n' +
      '5. Transmittals. Every signature is his. R. Halloway signs everything. ' +
      'It’s the one honest thing about him.',
    attachments: [
      {
        name: 'transmittal_scan.pdf',
        body:
          'BRENNAN ANALYTICAL LABS — RESULTS TRANSMITTAL\n' +
          'Attn: R. Halloway (SIGNED, RECEIVED Apr 2 2025)\n' +
          '"Bed 7 exceedances: DO NOT HARVEST. Worker contact not advised."\n' +
          '[stamp] RECEIVED TEN DAYS BEFORE THE DREDGE DETAIL.',
      },
    ],
  },
  {
    id: DRAFT_ID,
    account: 'tidewater',
    folder: 'drafts',
    from: 'Draft — never sent',
    subject: DRAFT_SUBJECT_CIPHER,
    when: 'Oct 11, 11:41 PM',
    body: DRAFT_BODY_CIPHER,
  },
];

export const emailById = (id: string): Email => {
  const e = EMAILS.find((x) => x.id === id);
  if (!e) throw new Error(`unknown email: ${id}`);
  return e;
};
